spring.application.name=shareme-webapp
spring.data.mongodb.uri=${MONGODB_URI}

#Frontend
frontend.url=${FRONTEND_URL}

server.port=${PORT:8080}

server.servlet.context-path=/api/v1.0

#generates the indexed
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

#Clerk
clerk.issuer=${CLERK_ISSUER}
clerk.jwks-url=${CLERK_JWKS_URL}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

#Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

#mongo db atlas
#mongodb+srv://<db_username>:<db_password>@cluster0.nig8gpx.mongodb.net/?appName=Cluster0